trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

  
steps:
  - task: Bash@3
    inputs:
      arguments: $(Build.Repository.Uri)
      targetType: inline
  - bash: |
      URL=$(Build.Repository.Uri)

      submodule_name=`echo "$URL" | awk -F "dolittle-" '{ $1 = "" ; print $0 }' | tr '[:upper:]' '[:lower:]'`

      mkdir tmp
      cd tmp/
      git clone https://github.com/dolittle/Documentation.git
      git submodule init && git submodule update Documentation/Source/repositories/$submodule_name
      cd Documentation/Source/repositories/$submodule_name
      git checkout master && git pull
      cd ../../../..
      git add Source/repositories/
      git commit -m "Updating Documentation" --username "Dolittle Documentation"
      git push
      cd ..
      rm -rf Documentation/