trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

  
steps:
  - task: Bash@3
    inputs:
      arguments: $(Build.Repository.Uri)
      targetType: inline
  - bash: |
      URL=$(Build.Repository.Uri)

      submodule_name=`echo "$URL" | awk -F "dolittle-" '{ print $2 }'`

      mkdir tmp
      cd tmp/
      git clone https://github.com/dolittle/Documentation.git
      cd Documentation/
      cd Source/
      cd repositories/
      git submodule init && git submodule update "$submodule_name"
      cd "$submodule_name"
      git checkout master && git pull
      cd ../../../..
      git add Source/repositories/
      git config user.name "mminguez"
      git commit -m "Updating Documentation"
      git push
      cd ..
      rm -rf Documentation/