trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

  
steps:
  - task: Bash@3
    inputs:
      arguments: $(Build.Repository.Uri)
      targetType: inline
  - bash: |

      URL=$1

      submodule_name=`echo "$URL" | awk -F "dolittle-" '{ $1 = "" ; print $0 }' | tr '[:upper:]' '[:lower:]'`

      echo $submodule_name
      mkdir tmp
      cd tmp/
      git config --global submodule.recurse
      git config --list
      git clone https://github.com/dolittle/Documentation.git
      cd Documentation/Source/repositories/
      git submodule init && git submodule update $submodule_name
      cd $submodule_name
      git checkout master && git pull
      cd ../../../..
      git add Source/repositories/
      git commit -m "Updating Documentation" --username "Dolittle Documentation"
      git push
      cd ..
      rm -rf Documentation/