trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

  
steps:
  - task: Bash@3
    inputs:
      arguments: $(Build.Repository.Uri)
      targetType: inline
  - bash: |

      URL=$1

      submodule_name=`echo "$URL" | awk -F "dolittle-" '{ $1 = "" ; print $0 }' | tr '[:upper:]' '[:lower:]'`

      echo $submodule_name
      mkdir tmp
      cd tmp/
      git config --global --list
      git config --list
      git clone --recurse-submodules="Source/repositories/$submodule_name" https://github.com/dolittle/Documentation.git
      